version: '3'
services:
  redis-stack-pubsub:
    image: redis/redis-stack
    volumes:
     - ./data/:/data     
     - ./local-redis-stack.conf:/redis-stack.conf 
    ports:
      - 6379:6379
      - 8001:8001

#$ docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
# sudo  docker run -p 6379:6379 -p 8001:8001 -v /local-data/:/data redis/redis-stack:latest